In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array+=1

In [4]:
array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
#matrix 
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
matrix[1,1]

5

In [7]:
matrix[:,1] #all rows, column 1

array([2, 5, 8])

In [8]:
matrix2 = matrix #matrix2 is a reference to matrix
matrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matrix2[1,1] = 100

In [10]:
matrix

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [11]:
matrix3 = matrix.copy() #matrix3 is a copy of matrix

In [12]:
kyle = np.arange(0,100,10)

In [13]:
kyle

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
mask= np.array([0,0,0,1,1,1,1,0,1,1], dtype = bool)
mask

array([False, False, False,  True,  True,  True,  True, False,  True,
        True])

In [15]:
kyle[mask]

array([30, 40, 50, 60, 80, 90])

In [16]:
random_array = np.random.rand(10)

In [17]:
random_array

array([0.59093244, 0.86949026, 0.867439  , 0.28411775, 0.32070084,
       0.04911005, 0.42762673, 0.19141026, 0.54010078, 0.66532806])

In [18]:
mask = random_array > 0.5
random_array[mask]

array([0.59093244, 0.86949026, 0.867439  , 0.54010078, 0.66532806])

In [19]:
np.where(random_array > 0.5) # return the index of the elements that are greater than 0.5


(array([0, 1, 2, 8, 9], dtype=int64),)

In [20]:
random_array[np.where(random_array > 0.5)]

array([0.59093244, 0.86949026, 0.867439  , 0.54010078, 0.66532806])

In [21]:
kyle1 = np.array([1,2,3,4,5])
np.asarray(kyle1, dtype = np.float32) #will not change the original array

array([1., 2., 3., 4., 5.], dtype=float32)

In [22]:
kyle1.astype(np.float32) #will not change the original array

array([1., 2., 3., 4., 5.], dtype=float32)

In [23]:
kyle1

array([1, 2, 3, 4, 5])

In [24]:
kyle3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.sum(kyle3, axis = 1) #sum of each row

array([ 6, 15, 24])

In [25]:
np.sum(kyle3, axis = 0) #sum of each column

array([12, 15, 18])

In [26]:
kyle3.prod(axis = 1) #product of each row

array([  6, 120, 504])

In [27]:
kyle3.prod(axis = 0) #product of each column

array([ 28,  80, 162])

In [28]:
kyle3.min(axis=0) #min of each column

array([1, 2, 3])

In [29]:
kyle3.min(axis=1) #min of each row

array([1, 4, 7])

In [30]:
kyle3.argmin(axis=0) #index of min of each column

array([0, 0, 0], dtype=int64)

In [31]:
kyle3.argmin(axis=1) #index of min of each row

array([0, 0, 0], dtype=int64)

In [32]:
kyle4 = np.array([[1.5,7.3,7.5], [2.3, 4.5, 6.7], [3.4, 5.6, 7.8]])

In [33]:
np.sort(kyle4)

array([[1.5, 7.3, 7.5],
       [2.3, 4.5, 6.7],
       [3.4, 5.6, 7.8]])

In [34]:
kyle5 = np.linspace(0, 10, 5)
kyle5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
values=np.array([2.5,6.5,9.5])
np.searchsorted(kyle5, values)

array([1, 3, 4], dtype=int64)

In [36]:
kyle5 = np.array([[1,0,6],
                [1,7,0],
                [2,3,1],
                [2,4,0]])
index = np.lexsort([-1*kyle5[:,0],kyle5[:,2]])
index

array([3, 1, 2, 0], dtype=int64)

In [37]:
kyle5[index]

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])

In [38]:
kyle6 = np.arange(10)
kyle6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
kyle6.shape

(10,)

In [40]:
kyle6.shape = (2,5)
kyle6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
kyle6.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
kyle7 =np.arange(10)
kyle7 = kyle7[np.newaxis, :]
kyle7.shape

(1, 10)

In [43]:
kyle7 = kyle7[np.newaxis,np.newaxis:]

In [44]:
kyle7.shape

(1, 1, 10)

In [45]:
kyle7=kyle7.squeeze()
kyle7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
kyle7.shape=(2,5)

In [47]:
kyle7.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [48]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2.5,3.5,4],[5.2,3,4],[7.5,4.3,8]])

In [49]:
c = np.concatenate((a,b), axis = 1)
c

array([[1. , 2. , 3. , 2.5, 3.5, 4. ],
       [4. , 5. , 6. , 5.2, 3. , 4. ],
       [7. , 8. , 9. , 7.5, 4.3, 8. ]])

In [50]:
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ],
       [2.5, 3.5, 4. ],
       [5.2, 3. , 4. ],
       [7.5, 4.3, 8. ]])

In [51]:
np.hstack((a,b))

array([[1. , 2. , 3. , 2.5, 3.5, 4. ],
       [4. , 5. , 6. , 5.2, 3. , 4. ],
       [7. , 8. , 9. , 7.5, 4.3, 8. ]])

In [52]:
a.flatten() #flatten the array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a.ravel() #flatten the array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [55]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
kyle8 = np.arange(10)
kyle8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.zeros_like(kyle8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
np.ones_like(kyle8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
np.identity(8) #identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [60]:
x = np.array([5,5])
y = np.array([2,2])
np.multiply(x,y)

array([10, 10])

In [61]:
np.dot(x,y) #dot product

20

In [62]:
x.shape = (2,1)
y.shape = (1,2)
np.dot(x,y)

array([[10, 10],
       [10, 10]])

In [63]:
kyle10 = np.arange(10)
np.random.shuffle(kyle10)
kyle10

array([6, 3, 2, 0, 5, 8, 1, 7, 9, 4])

In [64]:
np.random.seed(0)
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 10)

array([ 0.17640523,  0.04001572,  0.0978738 ,  0.22408932,  0.1867558 ,
       -0.09772779,  0.09500884, -0.01513572, -0.01032189,  0.04105985])

In [65]:
%%writefile kyle.txt
1 2 3 4 5 6
2 3 5 5 3 8

Overwriting kyle.txt


In [66]:
data= []
with open("kyle.txt") as f:
    for line in f:
        fields = line.split()
        cur_data=[float(x) for x in fields]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 5., 3., 8.]])

In [67]:
data=np.loadtxt("kyle.txt")

In [68]:
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 5., 3., 8.]])

In [69]:
#practice
np.__version__ # print the version of numpy

'1.19.5'

In [70]:
kk = np.zeros((3,3))
print('%d bytes'%(kk.size*kk.itemsize))

72 bytes


In [71]:
print(help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [72]:
kk1 =np.arange(10,50,1)[::-1]
kk1

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [73]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [74]:
np.random.random((3,3))


array([[0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675]])

In [75]:
kk2= np.ones((5,5)) 
kk2  = np.pad(kk2,pad_width=1,constant_values=0)
kk2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [76]:
print(np.unravel_index(100, (6,7,8))) # find the index of 100 in a 6*7*8 matrix

(1, 5, 4)


In [78]:
kk3 = np.random.random((5,5))
kk3_max = kk3.max()
kk3_min = kk3.min()
kk3 = (kk3-kk3_min)/(kk3_max-kk3_min) #normalize the matrix important!!!!
kk3

array([[0.63915963, 0.64350303, 0.12710061, 0.0357074 , 0.24496106],
       [0.29913352, 0.530809  , 0.38316027, 1.        , 0.0055466 ],
       [0.12541111, 0.07204108, 0.62383503, 0.17524418, 0.41424982],
       [0.16529659, 0.0694157 , 0.01489316, 0.62744926, 0.04609328],
       [0.11161691, 0.30475963, 0.81220043, 0.        , 0.83122006]])

In [80]:
kk4 = np.random.randint(0,10,10)
kk5 = np.random.randint(0,10,10)
print(kk4)
print(kk5)
np.intersect1d(kk4,kk5)

[2 9 1 4 6 8 2 3 0 0]
[6 0 6 3 3 8 8 8 2 3]


array([0, 2, 3, 6, 8])

In [82]:
today = np.datetime64('today', 'D')
today

numpy.datetime64('2023-04-13')

In [84]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
yesterday

numpy.datetime64('2023-04-12')

In [85]:
tommorow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
tommorow

numpy.datetime64('2023-04-14')

In [86]:
np.arange('2017-10', '2017-12', dtype='datetime64[D]')

array(['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04',
       '2017-10-05', '2017-10-06', '2017-10-07', '2017-10-08',
       '2017-10-09', '2017-10-10', '2017-10-11', '2017-10-12',
       '2017-10-13', '2017-10-14', '2017-10-15', '2017-10-16',
       '2017-10-17', '2017-10-18', '2017-10-19', '2017-10-20',
       '2017-10-21', '2017-10-22', '2017-10-23', '2017-10-24',
       '2017-10-25', '2017-10-26', '2017-10-27', '2017-10-28',
       '2017-10-29', '2017-10-30', '2017-10-31', '2017-11-01',
       '2017-11-02', '2017-11-03', '2017-11-04', '2017-11-05',
       '2017-11-06', '2017-11-07', '2017-11-08', '2017-11-09',
       '2017-11-10', '2017-11-11', '2017-11-12', '2017-11-13',
       '2017-11-14', '2017-11-15', '2017-11-16', '2017-11-17',
       '2017-11-18', '2017-11-19', '2017-11-20', '2017-11-21',
       '2017-11-22', '2017-11-23', '2017-11-24', '2017-11-25',
       '2017-11-26', '2017-11-27', '2017-11-28', '2017-11-29',
       '2017-11-30'], dtype='datetime64[D]')

In [89]:
kk6 = np.random.uniform(0,10,10)
kk6


array([5.33206254, 2.30533024, 3.94869293, 6.18808565, 4.74867515,
       4.70132189, 7.16074531, 2.87991004, 3.83462225, 7.49169837])

In [90]:
np.floor(kk6)

array([5., 2., 3., 6., 4., 4., 7., 2., 3., 7.])

In [92]:
kk7 = np.zeros((5,5))
kk7.flags.writeable = False # make the matrix unchangeable

In [99]:
import sys
np.set_printoptions(threshold=sys.maxsize) # print the whole matrix
kk8 = np.zeros((15,15))

kk8

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [103]:
kk9 = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(kk9-v)).argmin()
index
print(kk9[index])

35.404666208381016
35


In [106]:
kk10 = np.arange(10,dtype=np.int32)
kk10=kk10.astype(np.float32)
kk10.dtype

dtype('float32')

In [107]:
kk11 = np.arange(10).reshape(2,5)
for index, value in np.ndenumerate(kk11):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


In [111]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[3 7 9]
 [9 9 7]
 [3 2 3]]
[[3 2 3]
 [3 7 9]
 [9 9 7]]


In [113]:
kk13 = np.array([1,1,1,2,3,2,4,5,6,7,8,9,9,10])
np.bincount(kk13)

array([0, 3, 2, 1, 1, 1, 1, 1, 1, 2, 1], dtype=int64)

In [116]:
z= np.random.randint(0,10,(4,4,4,4))
print(z)
res = z.sum(axis=(-2,-1)) # sum the last two dimension
res

[[[[4 5 1 3]
   [6 7 4 0]
   [0 7 3 3]
   [0 0 9 4]]

  [[4 5 8 8]
   [0 1 5 9]
   [9 6 1 4]
   [0 4 7 7]]

  [[7 6 2 6]
   [0 2 7 7]
   [2 6 1 3]
   [7 0 5 4]]

  [[5 5 3 8]
   [0 1 5 4]
   [1 5 0 6]
   [8 8 6 3]]]


 [[[4 4 3 6]
   [5 9 8 1]
   [3 8 1 5]
   [8 0 3 7]]

  [[1 7 8 0]
   [7 5 9 9]
   [6 8 7 5]
   [9 1 0 0]]

  [[5 6 3 6]
   [1 7 7 0]
   [7 6 0 4]
   [2 7 5 2]]

  [[8 5 6 6]
   [4 1 5 4]
   [5 5 6 3]
   [8 1 4 2]]]


 [[[9 7 4 1]
   [8 2 3 3]
   [4 1 6 2]
   [5 4 9 1]]

  [[5 9 4 5]
   [7 4 4 2]
   [2 1 3 0]
   [1 9 1 6]]

  [[9 8 6 3]
   [0 7 3 2]
   [5 9 7 3]
   [4 7 6 7]]

  [[3 6 9 3]
   [7 1 3 7]
   [8 8 4 5]
   [3 6 9 6]]]


 [[[2 9 3 5]
   [7 9 0 7]
   [1 2 5 0]
   [5 8 9 8]]

  [[2 5 3 1]
   [7 3 8 5]
   [5 1 9 7]
   [2 1 0 1]]

  [[0 1 1 6]
   [8 8 3 2]
   [0 7 4 6]
   [0 5 3 3]]

  [[9 4 9 0]
   [6 5 3 0]
   [0 1 2 0]
   [2 2 9 6]]]]


array([[56, 78, 65, 68],
       [75, 82, 68, 73],
       [69, 63, 86, 88],
       [80, 60, 57, 58]])

In [118]:
z= np.arange(25).reshape(5,5)
z[[0,1]] = z[[1,0]] # swap the first two rows
z

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [121]:
kk15 = np.random.randint(0,10,50)
np.bincount(kk15).argmax() # find the most frequent number


3

In [122]:
kk16 = np.arange(10000)
np.random.shuffle(kk16)
n=5
print(kk16[np.argpartition(-kk16,n)[:n]]) # find the n largest number

[9998 9999 9997 9996 9995]


In [125]:
z = np.random.randint(0,5,(10,3))
np.set_printoptions(threshold=sys.maxsize)
z

array([[2, 4, 2],
       [2, 4, 2],
       [4, 0, 0],
       [1, 2, 2],
       [4, 2, 1],
       [3, 3, 0],
       [1, 0, 4],
       [3, 4, 1],
       [0, 0, 2],
       [1, 1, 0]])

In [127]:
e=np.all(z[:,1:]==z[:,:-1],axis=1) # find the same row
print(e) 

[False False False False False False False False False False]
